### ISSUE TITLE
对于TCP部分代码的一些不成熟的建议

### ISSUE THREAD

**Issue by dreamlike-ocean** [yuyenews/Magician#2]
1，ByteBuffer.allocate 使用的是堆内内存，改为ByteBuffer.allocateDirect可以利用零拷贝提高性能

2，循环读取没必要全部读完，全部读完再处理有OOM的风险，可以读一部分就开始处理，具体的“拆包”逻辑可以交由具体基于TCP的协议解析器负责

3，

这个位置不会抛出异常，没必要try…catch

```java
public TCPServer(EventGroup ioEventGroup, EventGroup workerEventGroup) {
        try {
            this.ioEventGroup = ioEventGroup;
            this.workerEventGroup = workerEventGroup;
            this.tcpServerConfig = new TCPServerConfig();
        } catch (Exception e) {
            log.error("打开serverSocketChannel，出现异常", e);
        }
    }
```

4,

EventGroup下面的所有EventRunner都公用一个线程池，建议中间这几个都删了，改为forkjoin线程池直接提交吧，也自带工作窃取

5，TCP server读，写，连接都在单线程中，瓶颈较大，可以尝试改为连接绑定某一线程单线读写，单线程做连接处理

这一段可以加入作为while的条件

```java
if(ioEventGroup.getThreadPool().isShutdown()){
                logger.error("ioEventGroup里的线程池关闭了，所以Selector也停止了");
                selector.close();
                serverSocketChannel.close();
                return;
            }
```

6，TCPServerMonitorTask#run()最后一行

```java
selector.wakeup();
```

我认为没有意义，这个操作是外部线程触发使得当前selector持有线程从select的阻塞 中唤醒，自己调用时已经是唤醒状态
7，TCP server是否与协议解析绑定太深？
8，EventLoop是个很好的模型，可以参考一些EventLoop的实现

**Comment by yuyenews** [comment]
好的，非常感谢。在后期的版本中我会慢慢迭代。

**Comment by zysaaa** [comment]
续：
1. TCPServerMonitorTask:
```
            int num = selector.select(3000);
            if (num <= 0) {
                continue;
            }
```
为什么不直接selector.select().

2.TCPServerMonitorTask#run()里进行wakeup的意义是什么，况且wakeup本身就是一个比较昂贵的操作

3.Acceptor&Poller模式会很大程度增加吞吐，1个acceptor负责处理accept事件，accept之后socketchannel注册到poller，poller线程负责这个socket后续的读写操作。 Tomcat#NioEndpoint，或netty都是类似的机制。我之前写过一个简单的，从1个线程处理连接读写到换成1个acceptor&1个poller，吞吐量差不多翻倍，多核的话甚至可以多个poller。 tomcat9目前是1个poller，tomcat8貌似是多个，但是作者好像认为多个poller提高不了太大的性能，所以直接换成1个poller了。但是连接和读写处理分开肯定有用

4.用到了很多LBQ，但是其实基本使用的是poll()方法而不是take()方法，并不要求没数据就阻塞，所以可以尝试考虑换成lock-free的队列，比如JCTools库提供的
